const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src/services/gemini.service.ts');
let content = fs.readFileSync(filePath, 'utf8');
const start = content.indexOf('  private parseJsonResponse<T>(responseText: string): T {');
const end = content.indexOf('  public async matchResumeWithJD(');
if (start === -1 || end === -1) {
  console.error('Could not find replacement boundaries');
  process.exit(1);
}
const replacementLines = [
  '  private convertJsLikeToJson(text: string) {',
  '    let converted = text',
  '      .replace(/^```(?:json)?\\s*/gi, "")',
  '      .replace(/\\s*```$/gi, "")',
  '      .trim();',
  '',
  '    converted = converted.replace(/`([^`]+)`/g, "\"$1\"");',
  '    converted = converted.replace(/([{,]\\s*)([A-Za-z0-9_\\- ]+)\\s*:/g, "$1\"$2\" :");',
  '    converted = converted.replace(/\'([^\']*)\'/g, (_, value) => {',
  '      return "\"" + value.replace(/\"/g, "\\\"") + "\"";',
  '    });',
  '    converted = converted.replace(/,\\s*([}\\]])/g, "$1");',
  '    return converted.trim();',
  '  }',
  '',
  '  private parseJsonResponse<T>(responseText: string): T {',
  '    const tryParse = (text: string) => {',
  '      try {',
  '        return JSON.parse(text);',
  '      } catch (_error) {',
  '        return null;',
  '      }',
  '    };',
  '',
  '    const cleaned = responseText',
  '      .trim()',
  '      .replace(/^```(?:json)?\\s*/i, "")',
  '      .replace(/\\s*```$/i, "")',
  '      .trim();',
  '',
  '    let parsed = tryParse(cleaned);',
  '    if (parsed !== null) {',
  '      return parsed;',
  '    }',
  '',
  '    const jsConverted = this.convertJsLikeToJson(cleaned);',
  '    parsed = tryParse(jsConverted);',
  '    if (parsed !== null) {',
  '      return parsed;',
  '    }',
  '',
  '    const braceStart = cleaned.indexOf("{");',
  '    const braceEnd = cleaned.lastIndexOf("}");',
  '    if (braceStart !== -1 && braceEnd !== -1 && braceStart < braceEnd) {',
  '      parsed = tryParse(cleaned.slice(braceStart, braceEnd + 1));',
  '      if (parsed !== null) {',
  '        return parsed;',
  '      }',
  '    }',
  '',
  '    const bracketStart = cleaned.indexOf("[");',
  '    const bracketEnd = cleaned.lastIndexOf("]");',
  '    if (bracketStart !== -1 && bracketEnd !== -1 && bracketStart < bracketEnd) {',
  '      parsed = tryParse(cleaned.slice(bracketStart, bracketEnd + 1));',
  '      if (parsed !== null) {',
  '        return parsed;',
  '      }',
  '    }',
  '',
  '    const strippedQuotes = cleaned.replace(/^["\'`\\s]+|["\'`\\s]+$/g, "").trim();',
  '    parsed = tryParse(strippedQuotes);',
  '    if (parsed !== null) {',
  '      return parsed;',
  '    }',
  '',
  '    console.error("Unable to parse JSON from Gemini response:", responseText);',
  '    throw new AppError("Unable to parse Gemini JSON response from model output", 500);',
  '  }',
  '',
  '  private normalizeArray(value: any): string[] {',
  '    if (Array.isArray(value)) {',
  '      return value.flatMap((item) => this.normalizeArray(item));',
  '    }',
  '    if (typeof value === "object" && value !== null) {',
  '      return Object.values(value).flatMap((item) => this.normalizeArray(item));',
  '    }',
  '    if (typeof value === "string") {',
  '      const trimmed = value.trim();',
  '      if (!trimmed) {',
  '        return [];',
  '      }',
  '      const parsed = this.parseJsonResponse<any>(trimmed);',
  '      if (Array.isArray(parsed)) {',
  '        return this.normalizeArray(parsed);',
  '      }',
  '      return trimmed',
  '        .split(/\\r?\\n|,/)    ',
  '        .map((item) => item.trim())',
  '        .filter(Boolean);',
  '    }',
  '    return [];',
  '  }',
  '',
  '  private normalizeAnalysisResult(raw: any) {',
  '    return {',
  '      skills: this.normalizeArray(raw.skills),',
  '      atsScore: typeof raw.atsScore === "number" ? raw.atsScore : Number(raw.atsScore) || 0,',
  '      suggestions: this.normalizeArray(raw.suggestions),',
  '      missingKeywords: this.normalizeArray(raw.missingKeywords),',
  '      improvedSummary: typeof raw.improvedSummary === "string"',
  '        ? raw.improvedSummary.trim()',
  '        : typeof raw.summary === "string"',
  '        ? raw.summary.trim()',
  '        : "",',
  '      experienceSuggestions: raw.experienceSuggestions ?? raw.experience ?? []',
  '    };',
  '  }',
  '',
  '  public async analyzeResumeText(resumeText: string) {',
  '    try {',
  '      const responseText = await this.generateText(`',
  '          Respond with only raw JSON. Do not include markdown fences, backticks, or any explanatory text.',
  '          Analyze the following resume text and extract the core skills, compute an ATS score (0-100), identify suggestions for improvements, identify missing keywords, rewrite a highly polished professional summary, and suggest concrete description/achievements enhancements.',
  '          Return an object with keys: skills, atsScore, suggestions, missingKeywords, improvedSummary, experienceSuggestions.',
  '',
  '          Resume Content:',
  '          "${resumeText}"',
  '        `);',
  '',
  '      const parsed = this.parseJsonResponse<any>(responseText);',
  '      return this.normalizeAnalysisResult(parsed);',
  '    } catch (error) {',
  '      console.error("Gemini Resume Analysis Error:", error);',
  '      throw new AppError("Failed to analyze resume via Gemini API: " + (error as Error).message, 500);',
  '    }',
  '  }'
];
const replacement = replacementLines.join('\n');
content = content.slice(0, start) + replacement + content.slice(end);
fs.writeFileSync(filePath, content, 'utf8');
console.log('Patched gemini.service.ts');
